#! /bin/bash

FIRST_INPUT=2 SECOND_INPUT=3 ARITHMETIC_OPERATION=ADDITION npm run operation
FIRST_INPUT=4 SECOND_INPUT=3 ARITHMETIC_OPERATION=SUBTRACTION npm run operation
FIRST_INPUT=5 SECOND_INPUT=6 ARITHMETIC_OPERATION=MULTIPLICATION npm run operation
FIRST_INPUT=2 SECOND_INPUT=3 ARITHMETIC_OPERATION=DIVISION npm run operation
FIRST_INPUT=999999999999999999999999999999 SECOND_INPUT=999999999999999999999999999999 ARITHMETIC_OPERATION=MULTIPLICATION npm run operation
FIRST_INPUT=12 SECOND_INPUT=7 ARITHMETIC_OPERATION=MODULO npm run operation
FIRST_INPUT=10 SECOND_INPUT=-2 ARITHMETIC_OPERATION=ADDITION npm run operation
FIRST_INPUT=-5 SECOND_INPUT=8 ARITHMETIC_OPERATION=MULTIPLICATION npm run operation
FIRST_INPUT=-11 SECOND_INPUT=4 ARITHMETIC_OPERATION=MULTIPLICATION npm run operation
FIRST_INPUT=0 SECOND_INPUT=0 ARITHMETIC_OPERATION=DIVISION npm run operation
FIRST_INPUT=4 SECOND_INPUT=0 ARITHMETIC_OPERATION=DIVISION npm run operation